name: Demo Workflow
on: [push]
jobs:
    Docker-Python-version:
        runs-on: ubuntu-latest
        steps:
            - run: docker --version
            - run: python --version 
    Pylint:
        runs-on: ubuntu-latest
        steps:
            - run: pip install pylint
            - run: pylint ../../app.py
    AppImage:
        runs-on: ubuntu-latest
        steps:
            - run: docker build --tag test-flask-app .
            - run: docker run -d -p 5000:5000 test-flask-app
