name: Demo Workflow
on: [push]
jobs:
    Docker-Python-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker --version
            - run: python --version 
    Pylint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: python3 -m venv tutorial-env
            - run: source tutorial-env/bin/activate
            - run: pip install pylint
            - run: sudo apt install python3-flask
            - run: pylint app.py
    AppImage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker build --tag test-flask-app .
            - run: docker run -d -p 5000:5000 test-flask-app
